# Generated by Django 5.1.15 on 2026-06-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('tag', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('gstin', models.CharField(blank=True, default='', max_length=32)),
                ('pan', models.CharField(blank=True, default='', max_length=32)),
                ('udyam', models.CharField(blank=True, default='', max_length=64)),
                ('stateName', models.CharField(blank=True, default='', max_length=64)),
                ('stateCode', models.CharField(blank=True, default='', max_length=8)),
                ('contact', models.TextField(blank=True, default='')),
                ('upiId', models.CharField(blank=True, default='', max_length=128)),
                ('upiQr', models.TextField(blank=True, default='')),
                ('bankName', models.CharField(blank=True, default='', max_length=128)),
                ('bankAccName', models.CharField(blank=True, default='', max_length=128)),
                ('bankAccNo', models.CharField(blank=True, default='', max_length=64)),
                ('bankIfsc', models.CharField(blank=True, default='', max_length=32)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('code', models.CharField(blank=True, default='', max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('cid', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(blank=True, default='', max_length=32)),
                ('username', models.CharField(blank=True, default='', max_length=128)),
                ('address', models.TextField(blank=True, default='')),
                ('stateName', models.CharField(blank=True, default='', max_length=64)),
                ('stateCode', models.CharField(blank=True, default='', max_length=8)),
                ('gstin', models.CharField(blank=True, default='', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('contactPersonName', models.CharField(blank=True, default='', max_length=255)),
                ('contactPersonPhone', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('doc_id', models.CharField(db_index=True, max_length=64)),
                ('number', models.CharField(blank=True, default='', max_length=128)),
                ('kind', models.CharField(blank=True, default='', max_length=16)),
                ('date_iso', models.CharField(blank=True, default='', max_length=64)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('doc_id', models.CharField(db_index=True, max_length=64)),
                ('number', models.CharField(blank=True, default='', max_length=128)),
                ('kind', models.CharField(blank=True, default='', max_length=16)),
                ('date_iso', models.CharField(blank=True, default='', max_length=64)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('sid', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('prefix', models.CharField(blank=True, default='', max_length=16)),
                ('sac', models.CharField(blank=True, default='', max_length=32)),
                ('rate', models.FloatField(default=0)),
                ('inclusive', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
